"""Operator, provenance, troubleshooting, and release-guidance resources."""

from __future__ import annotations

from exposure_scenario_mcp.benchmarks import load_benchmark_manifest
from exposure_scenario_mcp.models import (
    ReleaseMetadataReport,
    ReleaseReadinessReport,
    SecurityProvenanceReviewReport,
)
from exposure_scenario_mcp.validation import validation_manifest


def _benchmark_matrix_lines() -> list[str]:
    fixture = load_benchmark_manifest()
    lines = ["## Benchmark Matrix", ""]
    for case in fixture.get("cases", []):
        lines.append(
            f"- `{case['id']}` [{case['kind']}] {case['description']}"
        )
    return lines


def operator_guide() -> str:
    return """# Operator Guide

## Runtime Modes

- Use `stdio` for local agent-to-server execution. This is the safest default.
- Use `streamable-http` only when the server is behind trusted network controls.
- Prefer deterministic screening tools for route-specific scenario construction and use export tools
  only after the scenario is auditable.

## Standard Validation

Run these commands before changing defaults, schemas, or plugins:

```bash
uv run ruff check .
uv run pytest
uv run generate-exposure-contracts
```

## Release Validation

Run these commands before publishing a release artifact set:

```bash
uv run ruff check .
uv run pytest
uv build
uv run generate-exposure-contracts
uv run check-exposure-release-artifacts
```

## Interpretation Guardrails

- Treat every output as external-exposure context only.
- Do not reinterpret screening outputs as internal dose, BER, PoD, or final risk conclusions.
- Review `qualityFlags`, `limitations`, `uncertaintyRegister`, and `provenance` before using any
  scenario downstream.
- Treat `sensitivityRanking` as driver triage, not as a probabilistic uncertainty measure.

## Operational Checklist

- Confirm the defaults manifest version and SHA256 before benchmark or release runs.
- Run the release artifact verifier after `uv build` so published metadata matches `dist/`.
- Regenerate contracts whenever public schemas, examples, tools, or resources change.
- Keep ToxClaw and PBPK handoffs explicit; do not add hidden transformation logic in clients.
"""


def provenance_policy() -> str:
    return """# Provenance Policy

## Core Rules

- Every scenario, comparison, aggregate summary, and PBPK export must carry explicit provenance.
- Every applied default must appear in `exposureAssumptionRecord` output with a versioned source.
- Derived values remain visible as deterministic assumptions; they are not silently folded away.
- Every assumption now carries explicit governance metadata for evidence grade, applicability,
  uncertainty type, and default visibility.
- Every scenario now carries `tierSemantics` so screening outputs cannot quietly overclaim.

## Source Hierarchy

- `user_input`: explicit scenario inputs supplied by the caller.
- `default_registry`: values resolved from the versioned defaults pack.
- `derived`: deterministic runtime calculations generated by the active algorithm.

## Integrity Expectations

- The defaults pack is versioned and hashed with SHA256.
- Heuristic defaults must emit warning-quality flags so downstream users know they are still
  screening-level factors.
- ToxClaw-facing evidence exports use deterministic content hashes and stable IDs.

## Boundary

- Provenance demonstrates how external-dose outputs were produced.
- Provenance does not convert screening outputs into validated internal-dose or risk decisions.
"""


def uncertainty_framework() -> str:
    return """# Uncertainty Framework

## Tier A

- Deterministic point estimate plus explicit `uncertaintyRegister`.
- Deterministic one-at-a-time `sensitivityRanking`.
- Known dependencies preserved as `dependencyMetadata`.
- No probabilistic claims, confidence intervals, or population statements.

## Tier B

- Named deterministic scenario envelopes built from explicit archetypes.
- Deterministic parameter-bounds propagation from explicit lower and upper driver values.
- Envelope spans are bounded scenario sets, not confidence intervals.
- Parameter-bounds summaries are screening ranges, not population intervals or probabilistic claims.
- Driver attribution is based on explicit archetype differences, not Monte Carlo decomposition.

## Current Guardrail

- `v0.1.0` supports Tier A on every scenario output and Tier B via deterministic envelopes
  and parameter-bounds propagation.
- Probabilistic tiers remain blocked until validation evidence, dependency handling, and
  distribution governance mature.
"""


def validation_framework() -> str:
    manifest = validation_manifest()
    lines = [
        "# Validation Framework",
        "",
        "Current validation posture is verification plus benchmark regression.",
        "",
        "## Benchmark Domains",
        "",
    ]
    for item in manifest["benchmarkDomains"]:
        lines.append(
            f"- `{item['domain']}`: {', '.join(f'`{case_id}`' for case_id in item['caseIds'])}"
        )
    lines.extend(["", "## External Dataset Candidates", ""])
    for item in manifest["externalDatasets"]:
        lines.append(
            f"- `{item['datasetId']}` [{item['status']}] {item['observable']}: {item['note']}"
        )
    lines.extend(["", "## Notes", ""])
    lines.extend(f"- {item}" for item in manifest["notes"])
    return "\n".join(lines)


def troubleshooting_guide() -> str:
    return """# Troubleshooting

## Common Failures

- `comparison_chemical_mismatch`: the compared scenarios do not share the same `chemical_id`.
- `pbpk_body_weight_missing`: the scenario does not resolve `body_weight_kg`.
- `pbpk_inhalation_duration_missing`: inhalation PBPK export needs explicit event duration.
- `pbpk_unit_unsupported`: PBPK handoff accepts only canonical external dose units.
- `aggregate_component_duplicate`: aggregate inputs reused the same component scenario.

## Troubleshooting Sequence

1. Validate the request against the published schema resource.
2. Inspect `qualityFlags`, `limitations`, and `provenance` in the returned object.
3. Check the defaults manifest and defaults evidence map for the active factor source.
4. Re-run contract generation after changing any outward-facing schema or example.

## Remote Deployment Caution

- The server does not add authentication or origin enforcement on its own.
- If you expose `streamable-http`, put it behind trusted network controls or a gateway.
"""


def result_status_semantics() -> str:
    return """# Result Status Semantics

## Purpose

- Tool responses keep their existing `structuredContent` payload contracts.
- Future-safe execution state is published separately in top-level tool-result `_meta`.
- The metadata shape follows `toolResultMeta.v1`.

## Current v0.1 Behavior

- `executionMode` is always `sync`.
- `resultStatus` is `completed` for successful calls and `failed` for error results.
- `terminal` is always `true`.
- `queueRequired` is always `false`.
- `jobId` and `statusCheckUri` are `null`.

## Reserved Future States

- `accepted`: a request was accepted for asynchronous execution.
- `running`: execution is still in progress.
- Future async tools should reuse the same keys rather than inventing a second result style.

## Client Guidance

- Read `structuredContent` for the domain object.
- Read top-level `_meta` for execution semantics.
- Do not expect polling or queue semantics from the current deterministic release.
"""


def release_readiness_markdown(report: ReleaseReadinessReport) -> str:
    lines = [
        "# Release Readiness",
        "",
        report.summary,
        "",
        "## Status",
        "",
        f"- Release candidate: `{report.release_candidate}`",
        f"- Server: `{report.server_name}` `{report.server_version}`",
        f"- Defaults version: `{report.defaults_version}`",
        f"- Readiness status: `{report.status}`",
        "",
        "## Public Surface",
        "",
        f"- Tools: `{report.public_surface.tool_count}`",
        f"- Resources: `{report.public_surface.resource_count}`",
        f"- Prompts: `{report.public_surface.prompt_count}`",
        f"- Transports: {', '.join(f'`{item}`' for item in report.public_surface.transports)}",
        "",
        "## Validation Commands",
        "",
    ]
    lines.extend(f"- `{command}`" for command in report.validation_commands)
    lines.extend(["", "## Checks", ""])
    for check in report.checks:
        status = check.status.upper()
        lines.append(f"- `{check.check_id}` [{status}] {check.title}: {check.evidence}")
        if check.recommendation:
            lines.append(f"  next step: {check.recommendation}")
    lines.extend(["", *_benchmark_matrix_lines(), ""])
    lines.extend(["", "## Known Limitations", ""])
    lines.extend(f"- {item}" for item in report.known_limitations)
    return "\n".join(lines)


def security_provenance_review_markdown(report: SecurityProvenanceReviewReport) -> str:
    lines = [
        "# Security And Provenance Review",
        "",
        report.summary,
        "",
        "## Status",
        "",
        f"- Review ID: `{report.review_id}`",
        f"- Server: `{report.server_name}` `{report.server_version}`",
        f"- Defaults version: `{report.defaults_version}`",
        f"- Reviewed at: `{report.reviewed_at}`",
        f"- Review status: `{report.status}`",
        "",
        "## Reviewed Surface",
        "",
        f"- Tools: `{len(report.reviewed_surface.tool_names)}`",
        f"- Resources: `{len(report.reviewed_surface.resource_uris)}`",
        f"- Prompts: `{len(report.reviewed_surface.prompt_names)}`",
        "",
        "## Findings",
        "",
    ]
    for finding in report.findings:
        lines.append(
            f"- `{finding.finding_id}` [{finding.status.upper()}] {finding.title}: "
            f"{finding.evidence}"
        )
        if finding.recommendation:
            lines.append(f"  next step: {finding.recommendation}")
        if finding.references:
            lines.append(
                "  references: "
                + ", ".join(f"`{reference}`" for reference in finding.references)
            )
    lines.extend(["", "## External Requirements", ""])
    lines.extend(f"- {item}" for item in report.external_requirements)
    return "\n".join(lines)


def release_notes_markdown(report: ReleaseMetadataReport) -> str:
    lines = [
        "# Release Notes",
        "",
        (
            "Exposure Scenario MCP `v0.1.0` is the first public deterministic external-dose "
            "release candidate for the ToxMCP suite."
        ),
        "",
        "## Release Scope",
        "",
        "- Dermal, oral, and inhalation screening scenario construction",
        "- Aggregate/co-use summaries and auditable scenario comparison",
        "- PBPK handoff export aligned to the published PBPK MCP request shape",
        "- Deterministic ToxClaw evidence and refinement-bundle exports",
        "",
        "## Benchmark Summary",
        "",
        f"- Benchmark cases: `{report.benchmark_case_count}`",
        f"- Covered case IDs: {', '.join(f'`{item}`' for item in report.benchmark_case_ids)}",
        "",
        *_benchmark_matrix_lines(),
        "",
        "## Migration Notes",
        "",
    ]
    lines.extend(f"- {item}" for item in report.migration_notes)
    lines.extend(["", "## Validation Commands", ""])
    lines.extend(f"- `{item}`" for item in report.validation_commands)
    return "\n".join(lines)


def conformance_report_markdown(
    metadata: ReleaseMetadataReport,
    readiness: ReleaseReadinessReport,
    security_review: SecurityProvenanceReviewReport,
) -> str:
    lines = [
        "# Conformance Report",
        "",
        "This report summarizes the current release candidate against the published contract, "
        "benchmark, and review gates.",
        "",
        "## Status",
        "",
        f"- Package: `{metadata.package_name}` `{metadata.package_version}`",
        f"- Readiness: `{metadata.readiness_status}`",
        f"- Security/provenance review: `{metadata.security_review_status}`",
        f"- Contract schemas: `{metadata.contract_schema_count}`",
        f"- Contract examples: `{metadata.contract_example_count}`",
        "",
        "## Distribution Artifacts",
        "",
    ]
    for artifact in metadata.distribution_artifacts:
        availability = "present" if artifact.present else "not-built"
        details = [f"at `{artifact.relative_path}`"]
        if artifact.sha256 is not None:
            details.append(f"sha256 `{artifact.sha256[:16]}`")
        if artifact.size_bytes is not None:
            details.append(f"size `{artifact.size_bytes}` bytes")
        lines.append(
            f"- `{artifact.kind}` `{artifact.filename}` [{availability}] " + ", ".join(details)
        )
    lines.extend(["", "## Benchmark Coverage", ""])
    lines.append(f"- Benchmark cases published: `{metadata.benchmark_case_count}`")
    lines.extend(
        f"- `{case_id}`" for case_id in metadata.benchmark_case_ids
    )
    lines.extend(["", "## Release Gates", ""])
    for check in readiness.checks:
        lines.append(f"- `{check.check_id}` [{check.status.upper()}] {check.title}")
    lines.extend(["", "## Security Review Findings", ""])
    for finding in security_review.findings:
        lines.append(f"- `{finding.finding_id}` [{finding.status.upper()}] {finding.title}")
    return "\n".join(lines)
