"""Curate default sources by replacing heuristic citations with external regulatory sources."""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULTS_PATH = REPO_ROOT / "defaults" / "v1" / "core_defaults.json"
BENCHMARK_FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "benchmark_cases.json"

SOURCE_REPLACEMENTS = {
    "benchmark_population_defaults_v1": "epa_exposure_factors_handbook_2011",
    "heuristic_density_defaults_v1": "epa_exposure_factors_handbook_2011",
    "heuristic_retention_defaults_v1": ("rivm_cleaning_surface_contact_retention_defaults_2018"),
    "heuristic_transfer_efficiency_defaults_v1": ("rivm_cleaning_wet_cloth_transfer_defaults_2018"),
    "heuristic_incidental_oral_defaults_v1": ("sccs_notes_of_guidance_12th_revision_2023"),
    "heuristic_residual_spray_airborne_fraction_defaults_v1": (
        "rivm_disinfectant_trigger_spray_airborne_fraction_defaults_2006"
    ),
    "heuristic_time_limited_release_duration_defaults_v1": ("epa_exposure_factors_handbook_2011"),
    "inhalation_deposition_sink_heuristics_2026": ("echa_consumer_inhalation_room_defaults"),
    "native_residual_air_reentry_emission_heuristics_2026": (
        "rivm_general_fact_sheet_unspecified_room_defaults_2014"
    ),
    "heuristic_consexpo_pest_control_air_space_room_defaults_bridge_2026": (
        "rivm_general_fact_sheet_unspecified_room_defaults_2014"
    ),
}


def replace_sources(obj):
    """Recursively replace source_ids in the defaults JSON."""
    if isinstance(obj, dict):
        if "source_id" in obj and obj["source_id"] in SOURCE_REPLACEMENTS:
            obj["source_id"] = SOURCE_REPLACEMENTS[obj["source_id"]]
        # Handle special case for room_defaults which uses separate source_id keys
        for key, value in obj.items():
            if key.endswith("_source_id") and value in SOURCE_REPLACEMENTS:
                obj[key] = SOURCE_REPLACEMENTS[value]
            else:
                replace_sources(value)
    elif isinstance(obj, list):
        for item in obj:
            replace_sources(item)


def main() -> None:
    with DEFAULTS_PATH.open("r", encoding="utf-8") as f:
        defaults = json.load(f)

    old_version = defaults["defaults_version"]
    # Bump version: today with a new revision
    new_version = "2026.04.15.v34"

    replace_sources(defaults)
    defaults["defaults_version"] = new_version
    defaults["defaults_hash_sha256"] = ""  # Will be regenerated by tests/load

    with DEFAULTS_PATH.open("w", encoding="utf-8") as f:
        json.dump(defaults, f, indent=2, ensure_ascii=False)
        f.write("\n")

    # Update benchmark fixture
    with BENCHMARK_FIXTURE_PATH.open("r", encoding="utf-8") as f:
        fixture = json.load(f)

    fixture["defaults_version"] = new_version

    with BENCHMARK_FIXTURE_PATH.open("w", encoding="utf-8") as f:
        json.dump(fixture, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Updated defaults version: {old_version} -> {new_version}")


if __name__ == "__main__":
    main()
